return {
  -- 'folke/flash.nvim',
  -- event = 'VeryLazy',
  --
  -- opts = {
  --   modes = {
  --     search = {
  --       enabled = true,
  --     },
  --   },
  -- },
  -- keys = {
  --   {
  --     's',
  --     mode = { 'n', 'x', 'o' },
  --     function()
  --       require('flash').jump()
  --     end,
  --     desc = 'Flash',
  --   },
  --   {
  --     'r',
  --     mode = 'o',
  --     function()
  --       require('flash').remote()
  --     end,
  --     desc = 'Remote Flash',
  --   },
  -- },
  -- -- config = function()
  -- --   vim.api.nvim_set_hl(0, 'FlashLabel', { bg = 'NvimLightGreen' })
  -- -- end,
}
