-- vim.pack.add({
--   "https://github.com/nvim-lua/plenary.nvim",
--   "https://github.com/jiaoshijie/undotree",
-- })
--
-- require("undotree").setup({
--   float_diff = true,
--   layout = "left_bottom",
--   position = "left",
--   ignore_filetype = { "undotree", "undotreeDiff", "qf", "TelescopePrompt", "spectre_panel", "tsplayground" },
--   window = {
--     winblend = 0,
--   },
--   keymaps = {
--     ["<C-S-Down>"] = "move_next",
--     ["<C-S-Up>"] = "move_prev",
--     ["gj"] = "move2parent",
--     ["<M-S-Down>"] = "move_change_next",
--     ["<M-S-Up>"] = "move_change_prev",
--     ["<cr>"] = "action_enter",
--     ["p"] = "enter_diffbuf",
--     ["q"] = "quit",
--   },
-- })
--
-- vim.keymap.set("n", "<leader>ye", "<cmd>lua require('undotree').toggle()<cr>")
